=== ovitas/compass2/compass2/core/src/main/resources/no/ovitas/compass2/service/impl/compass2-config.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
  Compass2 config configuration DTD

  $Date: 2009-11-17$
  $Author: csanyi $
  $Version: 1.0$

  Barnabas Davoti - Ovitas AS
  Ferenc Magyar - ThotSoft KFT
  Attila Csanyi - ThotSoft KFT

-->
<!-- Compass2 config -->
<!ELEMENT compass2-config ( system-config, search-config? ) >

<!-- System config -->
<!ELEMENT system-config ( full-text-search, knowledge-base?, language-tools? ) >

<!-- Fulltext search -->
<!ELEMENT full-text-search ( full-text-search-implementation, content-indexer-implementation? ) >

<!ELEMENT full-text-search-implementation ( params? ) >
<!ATTLIST full-text-search-implementation class CDATA #REQUIRED >

<!ELEMENT params ( param+ ) >

<!ELEMENT param EMPTY >
<!ATTLIST param name CDATA #REQUIRED >
<!ATTLIST param value CDATA #REQUIRED >

<!ELEMENT content-indexer-implementation EMPTY >
<!ATTLIST content-indexer-implementation class CDATA #REQUIRED >


<!-- Knowledge base -->
<!ELEMENT knowledge-base ( knowlegde-base-implementation ) >

<!ELEMENT knowlegde-base-implementation ( params? ) >
<!ATTLIST knowlegde-base-implementation class CDATA #REQUIRED >

<!-- Language tools -->
<!ELEMENT language-tools ( language-tools-implementation ) >

<!ELEMENT language-tools-implementation ( params? ) >
<!ATTLIST language-tools-implementation class CDATA #REQUIRED >

<!-- Search config -->
<!ELEMENT search-config ( use-random-weigth?, max-topic-number-to-expand?, relation-types? ) >

<!ELEMENT use-random-weigth EMPTY >
<!ATTLIST use-random-weigth value CDATA #REQUIRED >

<!ELEMENT max-topic-number-to-expand EMPTY >
<!ATTLIST max-topic-number-to-expand value CDATA #REQUIRED >

<!-- Relation types -->
<!ELEMENT relation-types ( relation-type ) >

<!ELEMENT relation-type EMPTY >
<!ATTLIST relation-type generalization-weight CDATA #REQUIRED >
<!ATTLIST relation-type id CDATA #REQUIRED >
<!ATTLIST relation-type weight CDATA #REQUIRED >

=== ovitas/compass2/compass2/core/src/main/resources/no/ovitas/compass2/service/impl/compass2-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE compass2-config SYSTEM "compass2-config.dtd" >
<compass2-config>

	<system-config>
	    <full-text-search>
			<full-text-search-implementation class="${no.ovitas.compass2.service.FTSImplementation}" >
				<params>
					<param name="indexdirectory-path" value="${lucene.spellchecker.index.dir}"/>
					<param name="max-hits-per-query " value="${lucene.fts.max.hits.per.query}"/>
				</params>
			</full-text-search-implementation>
       		  
			<content-indexer-implementation class="${no.ovitas.compass2.service.fts.ContentIndexerImplementation}" />
			<document-repository path="${document.repository}" />
		</full-text-search>
		
		<knowledge-base>
			<knowlegde-base-implementation class="${no.ovitas.compass2.service.KBImplementation}" >
				<params>
					<param name="file-path" value="${knowledge.base.file}"/>
					<param name="load-on-startup" value="${knowladge.base.load.on.startup}"/>
				</params>
			</knowlegde-base-implementation>
		</knowledge-base>
		
		<language-tools>
			<language-tools-implementation class="${no.ovitas.compass2.service.LTImplementation}">
				<params>
					<param name="snowball-language" value="English"/>
					<param name="lucene-spellchecker-directory" value="${lucene.spellchecker.dir}"/>
					<param name="lucene-spellchecker-index-directory" value="${lucene.spellchecker.index.dir}"/>
					<param name="lucene-spellchecker-index-directory" value="${lucene.spellchecker.index.dir}"/>
					<param name="lucene-spellchecker-field" value="word"/>
					<param name="lucene-spellchecker-max-suggestion-num" value="${lucene.spellchecker.max.suggestion.num}"/>
				</params>
			</language-tools-implementation>
		</language-tools>
	</system-config>
  
	<search-config>
		<use-random-weigth value="${use.random.weight}"/>
		<max-topic-number-to-expand value="${max.topic.number.to.expand}" />
		
		<relation-types>
			<relation-type id="#123456" weight="0.5" generalization-weight="0.73" />
		</relation-types>
	</search-config>
	
</compass2-config>
