=== ovitas/compass2/core/src/main/config/compass2-config.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
  Compass2 config configuration DTD

  $Date: 2009-11-17$
  $Author: csanyi $
  $Version: 1.0$

  Barnabas Davoti - Ovitas AS
  Ferenc Magyar - ThotSoft KFT
  Attila Csanyi - ThotSoft KFT

-->

<!-- Compass2 config -->
<!ELEMENT compass2-config ( full-text-search, language-tools?, knowledge-bases?, result ) >

<!-- Fulltext search -->
<!ELEMENT full-text-search ( full-text-search-implementation, content-indexer-implementation? ) >
<!ATTLIST full-text-search
          prefix-match (yes | no) "no"
          fuzzy-match (yes | no) "no"
>

<!ELEMENT full-text-search-implementation ( params? ) >
<!ATTLIST full-text-search-implementation
          class CDATA #REQUIRED
>

<!ELEMENT params ( param+ ) >

<!ELEMENT param EMPTY >
<!ATTLIST param
          name CDATA #REQUIRED
          value CDATA #REQUIRED
>

<!ELEMENT content-indexer-implementation EMPTY >
<!ATTLIST content-indexer-implementation
          class CDATA #REQUIRED
>

<!-- Language tools -->
<!ELEMENT language-tools ( language-tools-implementation ) >

<!ELEMENT language-tools-implementation ( params? ) >
<!ATTLIST language-tools-implementation
          class CDATA #REQUIRED
>

<!-- Knowledge base -->
<!ELEMENT knowledge-bases ( knowledge-base* ) >

<!ELEMENT knowledge-base ( knowledge-base-implementation, expansion ) >
<!ATTLIST knowledge-base
          name CDATA #REQUIRED
>

<!ELEMENT knowledge-base-implementation ( params? ) >
<!ATTLIST knowledge-base-implementation
          class CDATA #REQUIRED
>

<!-- Expansion -->
<!ELEMENT expansion (association-types? ) >
<!ATTLIST expansion
          use-random-weight (yes | no) "no"
          expansion-threshold  CDATA #IMPLIED
          max-nr-of-topic-to-expand CDATA #IMPLIED
          hop-count CDATA #IMPLIED
>

<!-- Association types -->
<!ELEMENT association-types ( association-type+ ) >

<!ELEMENT association-type EMPTY >
<!ATTLIST association-type
          id CDATA #REQUIRED
          name CDATA #REQUIRED
          weight-ahead CDATA #REQUIRED           
          weight-aback CDATA #REQUIRED
>

<!-- Result -->
<!ELEMENT result EMPTY >
<!ATTLIST result
          result-threshold  CDATA #IMPLIED
          max-number-of-hits CDATA #IMPLIED
>

=== ovitas/compass2/compass2/core/src/main/config/compass2-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE compass2-config SYSTEM "compass2-config.dtd" >
<compass2-config>
    <full-text-search prefix-match="yes" fuzzy-match="no">
		<full-text-search-implementation class="${no.ovitas.compass2.service.FTSImplementation}" >
			<params>
				<param name="indexdirectory-path" value="${lucene.spellchecker.index.dir}"/>
				<param name="document-repository" value="${document.repository}"/>
			</params>
		</full-text-search-implementation>
		<content-indexer-implementation class="${no.ovitas.compass2.service.fts.ContentIndexerImplementation}" />
	</full-text-search>
	
	<language-tools>
		<language-tools-implementation class="${no.ovitas.compass2.service.LTImplementation}">
			<params>
				<param name="snowball-language" value="English"/>
				<param name="lucene-spellchecker-directory" value="${lucene.spellchecker.dir}"/>
				<param name="lucene-spellchecker-index-directory" value="${lucene.spellchecker.index.dir}"/>
				<param name="lucene-spellchecker-field" value="word"/>
				<param name="lucene-spellchecker-max-suggestion-num" value="${lucene.spellchecker.max.suggestion.num}"/>
			</params>
		</language-tools-implementation>
	</language-tools>
	
	<knowledge-bases>
		<knowledge-base name="${knowledge.base.name}">
			<knowledge-base-implementation class="${no.ovitas.compass2.service.KBImplementation}" >
				<params>
					<param name="file-path" value="${knowledge.base.file}"/>
					<param name="load-on-startup" value="${knowladge.base.load.on.startup}"/>
				</params>
			</knowledge-base-implementation>
			<expansion use-random-weight="no"  expansion-threshold="${expansion.threshold}" max-nr-of-topic-to-expand="${max.topic.number.to.expand}">
				<association-types>
					<association-type id="#t-11372557" name="TestAssocTypeName1" weight-ahead="0.5" weight-aback="0.7" />
					<association-type id="#t-11372561" name="TestAssocTypeName2" weight-ahead="0.5" weight-aback="0.7" />
					<association-type id="#t-1282034" name="TestAssocTypeName3" weight-ahead="0.5" weight-aback="0.7" />
					<association-type id="#t-1282040" name="TestAssocTypeName4" weight-ahead="0.5" weight-aback="0.7" />
					<association-type id="#t-1282046" name="TestAssocTypeName5" weight-ahead="0.5" weight-aback="0.7" />
					<association-type id="#t-1282238" name="TestAssocTypeName6" weight-ahead="0.5" weight-aback="0.7" />
					<association-type id="#t-1282244" name="TestAssocTypeName7" weight-ahead="0.5" weight-aback="0.7" />
					<association-type id="#t-1282403" name="TestAssocTypeName8" weight-ahead="0.5" weight-aback="0.7" />
					<association-type id="#t-1746221" name="TestAssocTypeName9" weight-ahead="0.5" weight-aback="0.7" />
					<association-type id="#t-3446294" name="TestAssocTypeName10" weight-ahead="0.5" weight-aback="0.7" />
					<association-type id="#t-1281990" name="TestAssocTypeName11" weight-ahead="0.5" weight-aback="0.7" />
					<association-type id="#t-2836564" name="TestAssocTypeName12" weight-ahead="0.5" weight-aback="0.7" />
					<association-type id="#t-1920472" name="TestAssocTypeName13" weight-ahead="0.5" weight-aback="0.7" />
					<association-type id="#t-1576847" name="TestAssocTypeName14" weight-ahead="0.5" weight-aback="0.7" />
					<association-type id="#t-1634400" name="TestAssocTypeName15" weight-ahead="0.5" weight-aback="0.7" />
					<association-type id="#t-1634404" name="TestAssocTypeName16" weight-ahead="0.5" weight-aback="0.7" />
					<association-type id="#t-1634406" name="TestAssocTypeName17" weight-ahead="0.5" weight-aback="0.7" />
					<association-type id="#t-1634408" name="TestAssocTypeName18" weight-ahead="0.5" weight-aback="0.7" />
					<association-type id="#t-1281994" name="TestAssocTypeName19" weight-ahead="0.5" weight-aback="0.7" />
					<association-type id="#t-11372542" name="TestAssocTypeName20" weight-ahead="0.5" weight-aback="0.7" />
					<association-type id="#t-11372544" name="TestAssocTypeName21" weight-ahead="0.5" weight-aback="0.7" />
					<association-type id="#t-2289089" name="TestAssocTypeName22" weight-ahead="0.5" weight-aback="0.7" />
					<association-type id="#t-1691635" name="TestAssocTypeName23" weight-ahead="0.5" weight-aback="0.7" />
					<association-type id="#t-1281982" name="TestAssocTypeName24" weight-ahead="0.5" weight-aback="0.7" />
					<association-type id="#t-1281984" name="TestAssocTypeName25" weight-ahead="0.5" weight-aback="0.7" />
					<association-type id="#t-1920474" name="TestAssocTypeName26" weight-ahead="0.5" weight-aback="0.7" />
					<association-type id="#t-3453352" name="TestAssocTypeName27" weight-ahead="0.5" weight-aback="0.7" />
					<association-type id="#t-2289087" name="TestAssocTypeName28" weight-ahead="0.5" weight-aback="0.7" />
					<association-type id="#t-1281988" name="TestAssocTypeName29" weight-ahead="0.5" weight-aback="0.7" />
					<association-type id="#t-1281992" name="TestAssocTypeName30" weight-ahead="0.5" weight-aback="0.7" />
					<association-type id="#t-1281980" name="TestAssocTypeName31" weight-ahead="0.5" weight-aback="0.7" />				
				</association-types>
			</expansion>
		</knowledge-base>
	</knowledge-bases>

	<result result-threshold="${result.threshold}" max-number-of-hits="${max.number.of.hits}"/>
</compass2-config>
