=== ovitas/compass2/compass2-core/src/main/config/compass2-config.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
  Compass2 config configuration DTD

  $Date: 2009-11-17$
  $Author: csanyi $
  $Version: 1.0$

  Barnabas Davoti - Ovitas AS
  Ferenc Magyar - ThotSoft KFT
  Attila Csanyi - ThotSoft KFT

-->

<!-- Compass2 config -->
<!ELEMENT compass2-config ( full-text-search-plugin?, language-tool-plugin?, knowledge-base-plugin, import-plugin, suggestion-provider-plugin?, referral-plugin?, search-fields, search-options ) >

<!-- Fulltext search -->
<!ELEMENT full-text-search-plugin ( full-text-search, indexer, content-handler-plugin, query-builder ) >
<!ATTLIST full-text-search-plugin
          
>

<!ELEMENT full-text-search ( implementation, params? ) >

<!ELEMENT implementation ( implementation-spring | implementation-reflection) >


<!ELEMENT implementation-spring ( context-files? ) >
<!ATTLIST implementation-spring
		  beanName CDATA #REQUIRED
>

<!ELEMENT implementation-reflection EMPTY >
<!ATTLIST implementation-reflection
			className CDATA #REQUIRED>

<!ELEMENT params ( param+ ) >

<!ELEMENT param EMPTY >
<!ATTLIST param
          name CDATA #REQUIRED
          value CDATA #REQUIRED
>

<!ELEMENT document-fields (field*) >

<!ELEMENT field EMPTY>
<!ATTLIST field
          name CDATA #REQUIRED
		  indexed (no|analyzed|not_analyzed|not_analyzed_no_norms|analyzed_no_norms) "analyzed"
		  stored (yes|no|compress) "yes"
		  type (string|number|date) "string"
>

<!ELEMENT indexer ( implementation, params? ) >

<!ELEMENT query-builder ( implementation, params? ) >

<!ELEMENT content-handler-plugin (content-handler+) >

<!ELEMENT content-handler (implementation, params?, document-fields?) >
<!ATTLIST content-handler
          type CDATA #REQUIRED
>

<!-- Language tools -->
<!ELEMENT language-tool-plugin (language-tool) >

<!ELEMENT language-tool ( implementation, params? ) >

<!-- Knowledge base -->
<!ELEMENT knowledge-base-plugin ( knowledge-base+ ) >
<!ATTLIST knowledge-base-plugin
		   default IDREF #REQUIRED
>

<!ELEMENT knowledge-base ( implementation, params?, topic-name-indexer, search-settings? ) >
<!ATTLIST knowledge-base
		   id ID #REQUIRED
>

<!ELEMENT topic-name-indexer ( implementation, params? ) >

<!ELEMENT search-settings ( knowledge-base-setting+ ) >

<!ELEMENT knowledge-base-setting ( options , scope* ) >
<!ATTLIST knowledge-base-setting
            name CDATA #REQUIRED
>

<!ELEMENT options EMPTY >
<!ATTLIST options
            tree (ahead | back | two_way) "ahead"
>
            
<!ELEMENT scope EMPTY >
<!ATTLIST scope
            name CDATA #REQUIRED
>            

<!ELEMENT context-files ( context-file* ) >

<!ELEMENT context-file EMPTY >
<!ATTLIST context-file
          file CDATA #REQUIRED
>

<!-- Search fields -->
<!ELEMENT search-fields ( search-field-string*, search-field-dateinterval*, search-field-numeric* ) >

<!ELEMENT search-field-string EMPTY >
<!ATTLIST search-field-string
		  index-field CDATA #REQUIRED
		  search-field CDATA #REQUIRED
		  type (string) "string"
		  default (true | false) "false"
		  weight CDATA #REQUIRED
		  match (match_all | match_any) "match_any"
		  fit (prefix | whole_word) "whole_word"
>

<!ELEMENT search-field-dateinterval EMPTY >
<!ATTLIST search-field-dateinterval
		  index-field CDATA #REQUIRED
		  search-field CDATA #REQUIRED
		  type (dateinterval) "dateinterval"
		  default (false) "false"
>

<!ELEMENT search-field-numeric EMPTY >
<!ATTLIST search-field-numeric
		  index-field CDATA #REQUIRED
		  search-field CDATA #REQUIRED
		  type (integer | float) "integer"
		  default (false) "false"
>



<!-- Result -->
<!ELEMENT search-options EMPTY >
<!ATTLIST search-options
          result-threshold  CDATA #REQUIRED
          max-number-of-hits CDATA #REQUIRED
		  hop-count CDATA #REQUIRED
		  prefix-match (true | false) "false"
		  fuzzy-match (true |false) "false"
		  tree-search (true |false) "false"
		  tree (ahead | back | two_way) "ahead"
		  max-nr-of-topic-to-expand CDATA #REQUIRED
		  expansion-threshold CDATA #REQUIRED
>

<!-- Import -->
<!ELEMENT import-plugin ( import* ) >


<!ELEMENT import ( implementation, params? ) >
<!ATTLIST import
		  type CDATA #REQUIRED
>

<!-- Suggestion Provider Plugin -->
<!ELEMENT suggestion-provider-plugin ( suggestion-provider ) >

<!ELEMENT suggestion-provider ( implementation, params? ) >

<!ELEMENT referral-plugin (referral) >
<!ELEMENT refferal ( implementation, params? ) >

=== ovitas/compass2/compass2-core/src/main/config/compass2-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE compass2-config SYSTEM "compass2-config.dtd" >
<compass2-config>
	<full-text-search-plugin>
		<full-text-search>
			<implementation>
				<implementation-reflection
					className="${no.ovitas.compass2.service.FTSImplementation}" />

			</implementation>
		</full-text-search>
		<indexer>
			<implementation>
				<implementation-reflection className="${no.ovitas.compass2.fts.IndexerImpl}" />

			</implementation>
			<params>
				<param name="indexdirectory-path" value="${lucene.fts.index.dir}" />
			</params>
		</indexer>
		<content-handler-plugin>
			<content-handler type="tika">
				<implementation>
					<implementation-reflection
						className="${no.ovitas.compass2.fts.ContentHandlerTikaImplementation}" />

				</implementation>
				<document-fields>
					<field name="URI" indexed="analyzed" stored="yes" type="string" />
					<field name="content" indexed="analyzed" stored="yes" type="string" />
					<field name="title" indexed="analyzed" stored="yes" type="string" />
					<field name="fileType" indexed="no" stored="yes" type="string" />
					<field name="lastModified" indexed="no" stored="yes" type="date" />
				</document-fields>
			</content-handler>
			<content-handler type="vsnorway">
				<implementation>
					<implementation-reflection
						className="${no.ovitas.compass2.fts.ContentHandlerVisitNorwayImplementation}" />
				</implementation>
				<document-fields>
					<field name="URI" indexed="not_analyzed_no_norms" stored="yes" type="string" />
					<field name="content" indexed="analyzed" stored="yes" type="string" />
					<field name="keyword" indexed="analyzed" stored="yes" type="string" />
					<field name="title" indexed="analyzed" stored="yes" type="string" />
					<field name="fileType" indexed="no" stored="yes" type="string" />
					<field name="lastModified" indexed="no" stored="yes" type="date" />
				</document-fields>
			</content-handler>
		</content-handler-plugin>
		<query-builder>
			<implementation>
				<implementation-reflection className="${no.ovitas.compass2.fts.QueryBuilder}" />
			</implementation>
		</query-builder>
	</full-text-search-plugin>

	<language-tool-plugin>
		<language-tool>
			<implementation>
				<implementation-reflection
					className="${no.ovitas.compass2.service.LTImplementation}" />

			</implementation>
			<params>
				<param name="snowball-language" value="English" />
				<param name="lucene-spellchecker-directory" value="${lucene.spellchecker.dir}" />
				<param name="lucene-spellchecker-index-directory" value="${lucene.spellchecker.index.dir}" />
				<param name="lucene-spellchecker-field" value="word" />
				<param name="lucene-spellchecker-max-suggestion-num" value="${lucene.spellchecker.max.suggestion.num}" />
			</params>
		</language-tool>
	</language-tool-plugin>

	<knowledge-base-plugin default="default">
		<knowledge-base id="default">
			<implementation>
				<implementation-spring
					beanName="${no.ovitas.compass2.service.KBImplementation.bean}">
					<context-files>
						<context-file file="classpath*:/applicationContext.xml" />
						<context-file file="classpath*:/applicationContext-dao.xml" />
						<context-file file="classpath*:/applicationContext-service.xml" />
					</context-files>
				</implementation-spring>
			</implementation>
			<params>
				<param name="importDir" value="${knowledgeBaseImportDir}" />
				<param name="tpMethod" value="${knowledgeBaseTPMethod}" />
			</params>
			<topic-name-indexer>
				<implementation>
					<implementation-reflection
						className="${no.ovitas.compass2.service.TopicNameIndexerImplementation}" />
				</implementation>
				<params>
					<param name="indexdirectory-path" value="${topic.name.index.dir}" />
				</params>
			</topic-name-indexer>
            <search-settings>
                <knowledge-base-setting name="vs old">
                    <options tree="ahead"/>
                    <scope name="EN;EN" />
                </knowledge-base-setting>
            </search-settings>
		</knowledge-base>
	</knowledge-base-plugin>

	<import-plugin>
		<import type="XTM10">
			<implementation>
				<implementation-reflection className="${import.xtm.xtm10importer}" />
			</implementation>
		</import>
		<import type="RDF">
			<implementation>
				<implementation-reflection className="${import.rdf.rdfimporter}" />
			</implementation>
		</import>
	</import-plugin>
	
	<suggestion-provider-plugin>
	   <suggestion-provider>
	       <implementation>
	           <implementation-reflection className="no.ovitas.compass2.suggestion.SuggestionProviderManagerImpl"/>
	       </implementation>
	       <params>
	           <param name="indexdirectory-path" value="${suggestion.index.dir}" />
	       </params>
	   </suggestion-provider>
	</suggestion-provider-plugin>

	<search-fields>
		<search-field-string index-field="keyword"
			search-field="Keyword" type="string" default="true" weight="5"
			match="match_any" fit="whole_word" />
		<search-field-string index-field="title"
			search-field="Title" type="string" default="true" weight="2" match="match_any"
			fit="whole_word" />
		<search-field-string index-field="content"
			search-field="Content" type="string" default="true" weight="1"
			match="match_all" fit="prefix" />
	</search-fields>

	<search-options result-threshold="${result.threshold}"
		max-number-of-hits="${max.number.of.hits}" hop-count="${hop.count}"
		prefix-match="${prefix.match}" fuzzy-match="${fuzzy.match}"
		tree-search="${tree.search}" tree="two_way" max-nr-of-topic-to-expand="${max.topic.number.to.expand}"
		expansion-threshold="${expansion.threshold}" />

</compass2-config>
